server:
  port: 8089
  servlet:
    encoding:
      charset: utf-8
      force: true
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:
logging:
  level:
    root: info
    org.springframework: debug
#    org.hibernate.type: trace
    org.springframework.security: info
