server:
  port: 8089
  servlet:
    encoding:
      charset: utf-8
      force: true
spring:
  devtools:
    livereload:
      enabled: true
  h2:
    console:
      enabled: true
#      settings:
#        web-allow-others: true
  datasource:
#    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    url: jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE #DB Close 막아두기..?
    driverClassName: org.h2.Driver
    username: sa
    password:
#    hikari:
#      connection-test-query: # 애플리케이션 실행시, 커넥션 확인하기 위한 테스트 쿼리 날린다.
  jpa:
    hibernate:
      ddl-auto: create-drop # 데이터베이스 초기화. schema.sql 또는 data.sql과 같이 쓰일 수 없다는 것 같음
logging:
  level:
    root: info
    org.springframework: debug
#    org.hibernate.type: trace
    org.springframework.security: info
